spring.application.name=task-management

spring.datasource.url=jdbc:postgresql://localhost:5433/taskdb
spring.datasource.username=admin
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=update

server.port=8096